name: Bump Version and Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    environment: GuaraniCoti

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bump version and create tag
        id: bump_version
        uses: phips28/gh-action-bump-version@v9
        with:
          tag-prefix: ""
          commit-message: "chore: bump version to {{version}}"
          tag-message: "Release version {{version}}"
          version-file: "VERSION"
          default-bump: "patch"
          create-tag: true
          push-to-remote: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: bump-version
    runs-on: ubuntu-latest
    environment: GuaraniCoti

    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        run: python -m twine upload dist/*s